apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    app: vote
spec:
  containers:
    - name: vote
      image: dockersamples/examplevotinapp_vote
      ports:
        - containerPort: 80
          name: vote